#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=2G

ynh_app_setting_set_default --key=php_memory_limit --value=2G

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

mv $install_dir/index.php $install_dir/www/index.php -f
mv $install_dir/app/ $install_dir/www/app/ -f
mv $install_dir/directory-lister.svg $install_dir/www/directory-lister.svg -f
mv $install_dir/LICENSE $install_dir/www/LICENSE -f
mv $install_dir/README.md $install_dir/www/README.md -f

#==============================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
